- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- .github/workflows/main.yaml
- .github/workflows/nightly.yaml
- .github/workflows/release.yaml
- .github/workflows/snapshot_release.yaml
- pom.xml
This PR introduces Github Actions Set up, including:
1. Issue (including bug report and feature request) and PR template.
2. Main CI, which will build and check `IT`.
3. Release and snapshot release.
/cc @kpavlov Would you please help me review this PR?
/cc @langchain4j BTW, for realease/snapshot release and IT, Could I just use your key and secret directly? (including Testcontainers Cloud, Deploy GPG key and so on...)
> Set up GitHub actions

- CONTRIBUTING.md
- README.md
> [Feature] Add contributing guide and README

- .github/workflows/main.yaml
- .github/workflows/nightly.yaml
- .github/workflows/release.yaml
Closes #
1. Remove Testcontainers Cloud in Github CI
2. add `-Dtinylog.writer.level=info` when runing IT.
> Update Github CI

- langchain4j-community-bom/pom.xml
- pom.xml
- web-search-engines/langchain4j-community-web-search-engine-searxng/pom.xml
- web-search-engines/langchain4j-community-web-search-engine-searxng/src/main/java/dev/langchain4j/community/web/search/searxng/SearXNGApi.java
- web-search-engines/langchain4j-community-web-search-engine-searxng/src/main/java/dev/langchain4j/community/web/search/searxng/SearXNGClient.java
- web-search-engines/langchain4j-community-web-search-engine-searxng/src/main/java/dev/langchain4j/community/web/search/searxng/SearXNGRequestLoggingInterceptor.java
- web-search-engines/langchain4j-community-web-search-engine-searxng/src/main/java/dev/langchain4j/community/web/search/searxng/SearXNGResponse.java
- web-search-engines/langchain4j-community-web-search-engine-searxng/src/main/java/dev/langchain4j/community/web/search/searxng/SearXNGResponseLoggingInterceptor.java
- web-search-engines/langchain4j-community-web-search-engine-searxng/src/main/java/dev/langchain4j/community/web/search/searxng/SearXNGResult.java
- web-search-engines/langchain4j-community-web-search-engine-searxng/src/main/java/dev/langchain4j/community/web/search/searxng/SearXNGResults.java
- web-search-engines/langchain4j-community-web-search-engine-searxng/src/main/java/dev/langchain4j/community/web/search/searxng/SearXNGWebSearchEngine.java
- web-search-engines/langchain4j-community-web-search-engine-searxng/src/test/java/dev/langchain4j/community/web/search/searxng/SearXNGWebSearchEngineIT.java
- web-search-engines/langchain4j-community-web-search-engine-searxng/src/test/resources/settings.yml
Closes #7 
Support for SearXNG as a web-search-engine
> [Feature] Integration with Searxng

- .github/workflows/main.yaml
Closes #18 
1. Build with JDK23 in Github Actions.
2. Run Integration test in PR
> build with latest jdk version

- langchain4j-community-bom/pom.xml
- models/langchain4j-community-qianfan/pom.xml
- pom.xml
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/pom.xml
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/main/java/dev/langchain4j/community/dashscope/spring/AutoConfig.java
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/main/java/dev/langchain4j/community/dashscope/spring/ChatModelProperties.java
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/main/java/dev/langchain4j/community/dashscope/spring/EmbeddingModelProperties.java
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/main/java/dev/langchain4j/community/dashscope/spring/LanguageModelProperties.java
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/main/java/dev/langchain4j/community/dashscope/spring/Properties.java
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/main/java/dev/langchain4j/community/dashscope/spring/TokenizerProperties.java
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/test/java/dev/langchain4j/community/dashscope/spring/AutoConfigIT.java
- spring-boot-starters/langchain4j-community-qianfan-spring-boot-starter/pom.xml
- spring-boot-starters/langchain4j-community-qianfan-spring-boot-starter/src/main/java/dev/langchain4j/community/qianfan/spring/AutoConfig.java
- spring-boot-starters/langchain4j-community-qianfan-spring-boot-starter/src/main/java/dev/langchain4j/community/qianfan/spring/ChatModelProperties.java
- spring-boot-starters/langchain4j-community-qianfan-spring-boot-starter/src/main/java/dev/langchain4j/community/qianfan/spring/EmbeddingModelProperties.java
- spring-boot-starters/langchain4j-community-qianfan-spring-boot-starter/src/main/java/dev/langchain4j/community/qianfan/spring/LanguageModelProperties.java
- spring-boot-starters/langchain4j-community-qianfan-spring-boot-starter/src/main/java/dev/langchain4j/community/qianfan/spring/Properties.java
- spring-boot-starters/langchain4j-community-qianfan-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- spring-boot-starters/langchain4j-community-qianfan-spring-boot-starter/src/test/java/dev/langchain4j/community/qianfan/spring/AutoConfigIT.java
- spring-boot-starters/pom.xml
- web-search-engines/langchain4j-community-web-search-engine-searxng/src/main/java/dev/langchain4j/community/web/search/searxng/SearXNGWebSearchEngine.java
Closes #
**Breaking changes!!**
1. Migrating `langchain4j-dashscope-spring-boot-starter` and `langchain4j-qianfan-spring-boot-starter`
2. Rename from `langchain4j-xxx-spring-boot-starter` to `langchain4j-community-xxx-spring-boot-starter`
3. Introducing a new `pom.xml` to manage dependencies of Spring Boot.
> Migrate Spring Boot starters of Qianfan and Dashscope

- embedding-stores/langchain4j-community-clickhouse/src/main/java/dev/langchain4j/community/store/embedding/clickhouse/ClickHouseSettings.java
- langchain4j-community-bom/pom.xml
- spring-boot-starters/langchain4j-community-clickhouse-spring-boot-starter/pom.xml
- spring-boot-starters/langchain4j-community-clickhouse-spring-boot-starter/src/main/java/dev/langchain4j/community/clickhouse/spring/ClickHouseEmbeddingStoreAutoConfiguration.java
- spring-boot-starters/langchain4j-community-clickhouse-spring-boot-starter/src/main/java/dev/langchain4j/community/clickhouse/spring/ClickHouseEmbeddingStoreProperties.java
- spring-boot-starters/langchain4j-community-clickhouse-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- spring-boot-starters/langchain4j-community-clickhouse-spring-boot-starter/src/test/java/dev/langchain4j/community/clickhouse/spring/ClickHouseEmbeddingStoreAutoConfigurationIT.java
- spring-boot-starters/pom.xml
Closes #37 
1. Add Spring Boot Starter for ClickHouse
> ClickHouse: Add Spring Boot starter

- embedding-stores/langchain4j-community-vearch/src/main/java/dev/langchain4j/community/store/embedding/vearch/VearchConfig.java
- embedding-stores/langchain4j-community-vearch/src/main/java/dev/langchain4j/community/store/embedding/vearch/VearchEmbeddingStore.java
Closes #48 
1. Adding `replicaNum` and `partitionNum` parameters in `VearchConfig`.
> Vearch: Add `replicaNum` and `partitionNum` configurable parameters

- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenChatModel.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenEmbeddingModel.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenHelper.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenLanguageModel.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenStreamingChatModel.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenStreamingLanguageModel.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenStreamingResponseBuilder.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenTokenizer.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/WanxHelper.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/QwenChatModelIT.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/QwenEmbeddingModelIT.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/QwenLanguageModelIT.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/QwenStreamingChatModelIT.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/QwenStreamingLanguageModelIT.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/QwenTokenizerIT.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/WanxImageModelIT.java
Support customization for all qwen models
> DashScope: Support customization for all qwen models

- embedding-stores/langchain4j-community-redis/pom.xml
- embedding-stores/langchain4j-community-redis/src/main/java/dev/langchain4j/community/store/embedding/redis/MetricType.java
- embedding-stores/langchain4j-community-redis/src/main/java/dev/langchain4j/community/store/embedding/redis/RedisEmbeddingStore.java
- embedding-stores/langchain4j-community-redis/src/main/java/dev/langchain4j/community/store/embedding/redis/RedisJsonUtils.java
- embedding-stores/langchain4j-community-redis/src/main/java/dev/langchain4j/community/store/embedding/redis/RedisMetadataFilterMapper.java
- embedding-stores/langchain4j-community-redis/src/main/java/dev/langchain4j/community/store/embedding/redis/RedisRequestFailedException.java
- embedding-stores/langchain4j-community-redis/src/main/java/dev/langchain4j/community/store/embedding/redis/RedisSchema.java
- embedding-stores/langchain4j-community-redis/src/main/java/dev/langchain4j/community/store/ememory/chat/redis/RedisChatMemoryStore.java
- embedding-stores/langchain4j-community-redis/src/main/java/dev/langchain4j/community/store/ememory/chat/redis/RedisChatMemoryStoreException.java
- embedding-stores/langchain4j-community-redis/src/test/java/dev/langchain4j/community/store/embedding/redis/RedisEmbeddingStoreIT.java
- embedding-stores/langchain4j-community-redis/src/test/java/dev/langchain4j/community/store/embedding/redis/RedisEmbeddingStoreRemovalIT.java
- embedding-stores/langchain4j-community-redis/src/test/java/dev/langchain4j/community/store/embedding/redis/RedisMetadataFilterMapperTest.java
- embedding-stores/langchain4j-community-redis/src/test/java/dev/langchain4j/community/store/memory/chat/redis/RedisChatMemoryStoreIT.java
- langchain4j-community-bom/pom.xml
- pom.xml
- spring-boot-starters/langchain4j-community-redis-spring-boot-starter/pom.xml
- spring-boot-starters/langchain4j-community-redis-spring-boot-starter/src/main/java/dev/langchain4j/community/store/embedding/redis/spring/RedisEmbeddingStoreAutoConfiguration.java
- spring-boot-starters/langchain4j-community-redis-spring-boot-starter/src/main/java/dev/langchain4j/community/store/embedding/redis/spring/RedisEmbeddingStoreProperties.java
- spring-boot-starters/langchain4j-community-redis-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- spring-boot-starters/langchain4j-community-redis-spring-boot-starter/src/test/java/dev/langchain4j/community/store/embedding/redis/spring/RedisEmbeddingStoreAutoConfigurationIT.java
- spring-boot-starters/pom.xml
Closes #
Migrate `langchain4j-redis` and `langchain4j-redis-spring-boot-starter`
> Migrate redis and spring-boot-starter

- models/langchain4j-community-dashscope/pom.xml
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/WanxHelper.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/WanxImageModel.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/WanxModelName.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/WanxImageModelIT.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/WanxTestHelper.java
Support wanx v2 models and their new features:
- wanx2.0-t2i-turbo: v2.0, cheaper than v2.1
- wanx2.1-t2i-turbo: v2.1, faster speed
- wanx2.1-t2i-plus: v2.1, better effect
> Support wanx v2 models and their new features

- web-search-engines/langchain4j-community-web-search-engine-searxng/pom.xml
- web-search-engines/langchain4j-community-web-search-engine-searxng/src/main/java/dev/langchain4j/community/web/search/searxng/SearXNGResponse.java
- web-search-engines/langchain4j-community-web-search-engine-searxng/src/test/java/dev/langchain4j/community/web/search/searxng/SearXNGWebSearchEngineIT.java
Closes #82 
1. Change `SearXNGResponse`
> Fix Searxng response data structure

- embedding-stores/langchain4j-community-neo4j/pom.xml
- embedding-stores/langchain4j-community-neo4j/src/main/java/dev/langchain4j/community/store/embedding/neo4j/Builder.java
- embedding-stores/langchain4j-community-neo4j/src/main/java/dev/langchain4j/community/store/embedding/neo4j/Neo4jEmbeddingStore.java
- embedding-stores/langchain4j-community-neo4j/src/main/java/dev/langchain4j/community/store/embedding/neo4j/Neo4jEmbeddingUtils.java
- embedding-stores/langchain4j-community-neo4j/src/test/java/dev/langchain4j/community/store/embedding/neo4j/Neo4jEmbeddingStoreIT.java
- embedding-stores/langchain4j-community-neo4j/src/test/java/dev/langchain4j/community/store/embedding/neo4j/Neo4jEmbeddingStoreRemovalIT.java
- langchain4j-community-bom/pom.xml
- pom.xml
> Migrating neo4j-embedding-store

- spring-boot-starters/langchain4j-community-clickhouse-spring-boot-starter/pom.xml
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/pom.xml
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/main/java/dev/langchain4j/community/dashscope/spring/ChatModelProperties.java
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/main/java/dev/langchain4j/community/dashscope/spring/EmbeddingModelProperties.java
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/main/java/dev/langchain4j/community/dashscope/spring/LanguageModelProperties.java
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/main/java/dev/langchain4j/community/dashscope/spring/Properties.java
- spring-boot-starters/langchain4j-community-qianfan-spring-boot-starter/pom.xml
- spring-boot-starters/langchain4j-community-qianfan-spring-boot-starter/src/main/java/dev/langchain4j/community/qianfan/spring/ChatModelProperties.java
- spring-boot-starters/langchain4j-community-qianfan-spring-boot-starter/src/main/java/dev/langchain4j/community/qianfan/spring/EmbeddingModelProperties.java
- spring-boot-starters/langchain4j-community-qianfan-spring-boot-starter/src/main/java/dev/langchain4j/community/qianfan/spring/LanguageModelProperties.java
- spring-boot-starters/langchain4j-community-qianfan-spring-boot-starter/src/main/java/dev/langchain4j/community/qianfan/spring/Properties.java
- spring-boot-starters/langchain4j-community-redis-spring-boot-starter/pom.xml
- spring-boot-starters/langchain4j-community-vearch-spring-boot-starter/pom.xml
- spring-boot-starters/langchain4j-community-xinference-spring-boot-starter/pom.xml
- spring-boot-starters/pom.xml
Closes #104 
1. Fix `spring-boot-configuration-processor` not working.
2. Remove lombok in `langchain4j-community-qianfan-spring-boot-starter`.
> Spring Boot: handle `spring-boot-configuration-processor` properly

- langchain4j-community-bom/pom.xml
- spring-boot-starters/langchain4j-community-neo4j-spring-boot-starter/pom.xml
- spring-boot-starters/langchain4j-community-neo4j-spring-boot-starter/src/main/java/dev/langchain4j/community/neo4j/spring/Neo4jEmbeddingStoreAutoConfiguration.java
- spring-boot-starters/langchain4j-community-neo4j-spring-boot-starter/src/main/java/dev/langchain4j/community/neo4j/spring/Neo4jEmbeddingStoreProperties.java
- spring-boot-starters/langchain4j-community-neo4j-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- spring-boot-starters/langchain4j-community-neo4j-spring-boot-starter/src/test/java/dev/langchain4j/community/neo4j/spring/Neo4jEmbeddingStoreAutoConfigurationIT.java
- spring-boot-starters/pom.xml
Closes #
Added Neo4j Spring Boot Starter: https://github.com/langchain4j/langchain4j-community/pull/103#pullrequestreview-2705824937
> Add Neo4j Spring Boot Starter

- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenHelper.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/QwenAiServicesWithToolsIT.java
Closes https://github.com/langchain4j/langchain4j/issues/2808
Allow whitespace characters in the model's answer.
> fix: allow whitespace characters in the model's answer

- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/QwenAiServicesIT.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/QwenChatModelIT.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/QwenStreamingAiServiceIT.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/QwenStreamingChatModelIT.java
Add QwenAiServicesIT and QwenStreamingAiServiceIT.
Provide the mirror urls of the test images.
> DashScope: Optimize ITs, and try to make all of them happy

- embedding-stores/langchain4j-community-neo4j/src/test/java/dev/langchain4j/community/store/embedding/neo4j/Neo4jEmbeddingStoreBaseTest.java
- Fix flaky Neo4jEmbedding ensureStoreIsEmpty test.
See here: https://github.com/langchain4j/langchain4j-community/actions/runs/14649577148/job/41111886216?pr=116#step:5:5340
Theoretically the `DROP INDEX` after the tests is not strictly needed, since the tests work anyway because there is an `IF NOT EXISTS` that does not cause the execution to fail if it finds an equivalent index.
Not sure why locally it always works even when starting all the tests together and why on the IC it seems to always fail to show up and also fails on the PR where Neo4jEmbeddingStore was not changed.
But probably the tests are run in different order and it could happen that `EmbeddingStore.search(..)` method which calls the `queryNodes(indexName, ...)` is done after the `DROP INDEX ...` but before the `CREATE …
> [DRAFT] Fix Neo4jEmbedding ensureStoreIsEmpty test

- embedding-stores/langchain4j-community-alloydb-pg/src/test/java/dev/langchain4j/community/store/embedding/alloydb/AlloyDBEmbeddingStoreIT.java
- embedding-stores/langchain4j-community-alloydb-pg/src/test/java/dev/langchain4j/community/store/embedding/alloydb/AlloyDBEmbeddingStoreRemovalIT.java
> tests(alloydb): add retry to embedding store init

- models/langchain4j-community-zhipu-ai/pom.xml
- models/langchain4j-community-zhipu-ai/src/main/java/dev/langchain4j/community/model/zhipu/ZhipuAiClient.java
- models/langchain4j-community-zhipu-ai/src/main/java/dev/langchain4j/community/model/zhipu/shared/ErrorResponse.java
- models/langchain4j-community-zhipu-ai/src/main/java/dev/langchain4j/community/model/zhipu/shared/SensitiveFilter.java
- models/langchain4j-community-zhipu-ai/src/test/java/dev/langchain4j/community/model/zhipu/ZhipuAiChatModelIT.java
- models/langchain4j-community-zhipu-ai/src/test/java/dev/langchain4j/community/model/zhipu/ZhipuAiEmbeddingModelIT.java
- models/langchain4j-community-zhipu-ai/src/test/java/dev/langchain4j/community/model/zhipu/ZhipuAiImageModelIT.java
- models/langchain4j-community-zhipu-ai/src/test/java/dev/langchain4j/community/model/zhipu/ZhipuAiStreamingChatModelIT.java
- models/langchain4j-community-zhipu-ai/src/test/java/dev/langchain4j/community/model/zhipu/common/ZhipuAiAiServicesIT.java
- models/langchain4j-community-zhipu-ai/src/test/java/dev/langchain4j/community/model/zhipu/common/ZhipuAiAiServicesWithToolsIT.java
- models/langchain4j-community-zhipu-ai/src/test/java/dev/langchain4j/community/model/zhipu/common/ZhipuAiChatModelListenerIT.java
- models/langchain4j-community-zhipu-ai/src/test/java/dev/langchain4j/community/model/zhipu/common/ZhipuAiStreamingAiServicesIT.java
- models/langchain4j-community-zhipu-ai/src/test/java/dev/langchain4j/community/model/zhipu/common/ZhipuAiStreamingChatModelListenerIT.java
Closes #49 
1. Add more common tests about `langchain4j-community-zhipu-ai` (Some tests failed)
2. Fix json parsing in `ErrorResponse`.
> ZhipuAi: Fix json parsing in `ErrorResponse` and add more common tests

- models/langchain4j-community-dashscope/pom.xml
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenChatModel.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenChatRequestParameters.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenChatResponseMetadata.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenHelper.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenModelName.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenStreamingChatModel.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/QwenChatModelIT.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/QwenStreamingChatModelIT.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/QwenTestHelper.java
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/main/java/dev/langchain4j/community/dashscope/spring/AutoConfig.java
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/main/java/dev/langchain4j/community/dashscope/spring/ChatModelProperties.java
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/test/java/dev/langchain4j/community/dashscope/spring/AutoConfigIT.java
Closes #
- Bump dashscope sdk version to 2.20.0
- Add Qwen3 model names and tests.
- Add a parameter for thinking mode.
- Fix testing issues introduced during langchain4j refactoring.
> DashScope: Introduce Qwen3 and the thinking mode parameter

- content-retrievers/langchain4j-community-neo4j-retriever/src/main/java/dev/langchain4j/community/rag/content/retriever/neo4j/KnowledgeGraphWriter.java
- content-retrievers/langchain4j-community-neo4j-retriever/src/test/java/dev/langchain4j/community/rag/content/retriever/neo4j/Neo4jKnowledgeGraphWriterBaseTest.java
- content-retrievers/langchain4j-community-neo4j-retriever/src/test/java/dev/langchain4j/community/rag/content/retriever/neo4j/Neo4jKnowledgeGraphWriterTest.java
- embedding-stores/langchain4j-community-neo4j/src/main/java/dev/langchain4j/community/store/embedding/neo4j/Neo4jEmbeddingStore.java
Closes #216
Currently in Langchain4j we can create a Neo4j KnowledgeGraph via the [KnowledgeGraphWriter](https://github.com/langchain4j/langchain4j-community/blob/main/content-retrievers/langchain4j-community-neo4j-retriever/src/main/java/dev/langchain4j/community/rag/content/retriever/neo4j/KnowledgeGraphWriter.java) class,
but to retrieve the results we would have to use manual queries (e.g. `MATCH (c:Chunk)-[]->(:Document) RETURN c).
To create something similar, i.e. with text embedded from the document texts,
added an argument  to `KnowledgeGraphWriter` constructor, so that we can store and retrieve vector via Neo4jEmbeddingStore.
> Add the ability to store the KnowledgeGraphWriter results in vector indexes via Neo4jEmbeddingStore

- models/langchain4j-community-qianfan/pom.xml
- models/langchain4j-community-qianfan/src/main/java/dev/langchain4j/community/model/qianfan/QianfanChatModel.java
- models/langchain4j-community-qianfan/src/main/java/dev/langchain4j/community/model/qianfan/QianfanStreamingChatModel.java
- spring-boot-starters/langchain4j-community-qianfan-spring-boot-starter/src/main/java/dev/langchain4j/community/qianfan/spring/AutoConfig.java
- spring-boot-starters/langchain4j-community-qianfan-spring-boot-starter/src/main/java/dev/langchain4j/community/qianfan/spring/ChatModelProperties.java
Closes #230 and part of #182 
1. Add `maxOutputTokens`, `userId` and `stop` in `QianfanStreamingChatModel`
2. Support `ChatRequestParameters` properly.
> Qianfan: support `ChatRequestParameters` properly

- models/langchain4j-community-chatglm/src/main/java/dev/langchain4j/community/model/chatglm/ChatGlmChatModel.java
Closes part of #182
1. Support `ChatRequestParameters` correctly.
2. Mark as `@Deprecated`. (chatglm is a very old model and zhipu-ai is official provider of chatglm)
> ChatGLM: support ChatRequestParameters and mark as deprecated

- models/langchain4j-community-xinference/src/main/java/dev/langchain4j/community/model/xinference/XinferenceChatModel.java
- models/langchain4j-community-xinference/src/main/java/dev/langchain4j/community/model/xinference/XinferenceStreamingChatModel.java
Closes part of #182 
1. Support `ChatRequestParameters`.
> Xinference: support ChatRequestParameters

- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenChatModel.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenChatRequestParameters.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenHelper.java
- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenStreamingChatModel.java
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/main/java/dev/langchain4j/community/dashscope/spring/AutoConfig.java
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/main/java/dev/langchain4j/community/dashscope/spring/ChatModelProperties.java
- spring-boot-starters/langchain4j-community-dashscope-spring-boot-starter/src/test/java/dev/langchain4j/community/dashscope/spring/AutoConfigIT.java
1. Make sanitizeMessages() throw more appropriate exception types.
2. Qwen includes a lot models. These models may not follow a uniform message order constraint. Therefore, an enableSanitizeMessages option has been introduced to control whether the langchain4j framework sanitize input messages.
3. I tested the latest qwen-max (which should be a qwen3), and the constraint on message order seems to have become more insensitive.   
For instance, messages like ("assistant", "assistant", "system") do not trigger any error. This differs from the description in the documentation, which says that the system message must be placed first in the list. The actual requirements for message order have become unclear.   
However, the qwen2 model remains sensitive to message order. Considering that people …
> DashScope: Introduce enableSanitizeMessages option

- embedding-stores/langchain4j-community-redis/src/main/java/dev/langchain4j/community/store/embedding/redis/RedisEmbeddingStore.java
- embedding-stores/langchain4j-community-redis/src/test/java/dev/langchain4j/community/store/embedding/redis/RedisEmbeddingStoreIT.java
- spring-boot-starters/langchain4j-community-redis-spring-boot-starter/src/main/java/dev/langchain4j/community/store/embedding/redis/spring/RedisEmbeddingStoreAutoConfiguration.java
- spring-boot-starters/langchain4j-community-redis-spring-boot-starter/src/test/java/dev/langchain4j/community/store/embedding/redis/spring/RedisEmbeddingStoreAutoConfigurationIT.java
Closes #260 
1. Add custom `JedisPooled` and `JedisClientConfig` for user to customize redis client.
2. Remove `AutoCloseable` to let users manage redis client.
3. Fix authorization issue when user is null but password is not null.
/cc @lzx1026078111 @zzx1314
> Redis: fix wrong authorization check

- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/QwenChatResponseMetadata.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/QwenStreamingAiServiceIT.java
Closes #270 
1. QwenChatResponseMetadata override the `toBuilder()` function.
2. reviewed other models, only the model which extend the ChatResponseMetadata may have this problem. In langchain-community, only Qwen extend the ChatResponseMetadata, so no other model have this problem.
> fix ChatResponseMetadata type not inconsistent

- models/langchain4j-community-dashscope/src/main/java/dev/langchain4j/community/model/dashscope/WanxImageModel.java
- models/langchain4j-community-dashscope/src/test/java/dev/langchain4j/community/model/dashscope/WanxImageModelIT.java
wanx2.1-t2i-turbo model will return error code when prompt contains illegal info which caused IndexOutOfBounds Exception when processing response.
Closes #
> fix: WanxImageModel Image response list IndexOutOfBound

- langchain4j-community-core/src/main/java/dev/langchain4j/community/rag/content/aggregator/MmrContentAggregator.java
- langchain4j-community-core/src/main/java/dev/langchain4j/community/rag/content/aggregator/strategy/EmbeddingStrategy.java
- langchain4j-community-core/src/main/java/dev/langchain4j/community/rag/content/aggregator/strategy/EmbeddingStrategyFactory.java
- langchain4j-community-core/src/main/java/dev/langchain4j/community/rag/content/aggregator/strategy/GenerateEmbeddings.java
- langchain4j-community-core/src/main/java/dev/langchain4j/community/rag/content/aggregator/strategy/HybridEmbeddings.java
- langchain4j-community-core/src/main/java/dev/langchain4j/community/rag/content/aggregator/strategy/UseExistingEmbeddings.java
- langchain4j-community-core/src/main/java/dev/langchain4j/community/rag/content/retriever/EmbeddingStoreContentRetriever.java
- langchain4j-community-core/src/main/java/dev/langchain4j/community/rag/content/util/EmbeddingMetadataUtils.java
- langchain4j-community-core/src/main/java/dev/langchain4j/community/store/embedding/MmrSelector.java
- langchain4j-community-core/src/test/java/dev/langchain4j/community/rag/content/aggregator/MmrContentAggregatorTest.java
- langchain4j-community-core/src/test/java/dev/langchain4j/community/rag/content/retriever/EmbeddingStoreContentRetrieverTest.java
- langchain4j-community-core/src/test/java/dev/langchain4j/community/store/embedding/MmrSelectorTest.java
Closes #325
Integrates Maximum Marginal Relevance (MMR) algorithm into `ReRankingContentAggregator` to balance relevance and diversity when selecting documents for LLM context.
1. **`MmrSelector`** - Low-level utility class implementing MMR algorithm
- Stateless utility operating on `EmbeddingMatch` objects
- Configurable lambda parameter (0.0-1.0) for relevance vs diversity balance
- Uses existing scores when available, falls back to cosine similarity calculation
- Comprehensive parameter validation and edge case handling
2. **Enhanced `ReRankingContentAggregator`**
- New optional constructor parameter `lambda` for MMR configuration
- Builder pattern support with `.lambda(double)` method
- MMR re-ranking integrated into existing `reRankAndFilter` method
- Backward compatibility …
> feat: Integrate MMR algorithm into ReRankingContentAggregator 

- models/langchain4j-community-oci-genai/src/main/java/dev/langchain4j/community/model/oracle/oci/genai/BaseGenericChatModel.java
- models/langchain4j-community-oci-genai/src/test/java/dev/langchain4j/community/model/oracle/oci/genai/OciGenAiChatModelIT.java
Fixes #389
Fix tool parameter mapping
> Tool parameters fix #389

- models/langchain4j-community-oci-genai/src/main/java/dev/langchain4j/community/model/oracle/oci/genai/GenericStreamingResponseBuilder.java
- models/langchain4j-community-oci-genai/src/main/java/dev/langchain4j/community/model/oracle/oci/genai/OciGenAiChatModel.java
- models/langchain4j-community-oci-genai/src/main/java/dev/langchain4j/community/model/oracle/oci/genai/OciGenAiStreamingChatModel.java
- models/langchain4j-community-oci-genai/src/test/java/dev/langchain4j/community/model/oracle/oci/genai/GenericStreamingChatModelIT.java
- models/langchain4j-community-oci-genai/src/test/java/dev/langchain4j/community/model/oracle/oci/genai/GenericStreamingTest.java
- models/langchain4j-community-oci-genai/src/test/resources/tinylog.properties
Fixes #392
Fixes a bug in merging partial tool arguments in Generic OCI GenAi streaming model
> OCI GenAi - Streaming tool merge fix #392
